name: Test
on:
  pull_request:
    branches:
    - master

jobs:
  test:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: "0"
    - name: Build image
      run: make docker
      env:
        VERSION: test
    - name: Run image
      run: docker run --rm docker.io/vshn/signalilo:test --version
  test_go_get:
    # Only run `go get` tests on PRs with source branch in
    # github.com/saremox/signalilo, as go get will fail for PRs whose source
    # branch is in a fork.
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.23', '1.24' ]
    name: Go install with Go ${{ matrix.go }}
    steps:
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}
    - run: go install -v github.com/saremox/signalilo@${{ github.head_ref }}
      env:
        GO111MODULE: on
        GOPROXY: direct
    - run: signalilo --version
